# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# Baidu Analytics
# baidu_analytics: 9e0cbea7d3319c6c94c71dfb93c151b8

# Google Analytics
google_analytics: UA-74273646-1

# Duoshuo
# duoshuo_shortname: ahonn

# Disqus
disqus_shortname: ahonn

# Social links
social:
  github: https://github.com/ahonn
  twitter: https://twitter.com/jiang_ahonn
  # weibo: http://weibo.com/ahonn
